# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Zapytanie')),
                ('seaech_engine', models.IntegerField(verbose_name='Wyszukiwarka')),
                ('status', models.IntegerField(verbose_name='Ststus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to=settings.AUTH_USER_MODEL, verbose_name='U\u017cytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytu\u0142')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Opis')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='seresults.SearchRequest', verbose_name='Zapytanie')),
            ],
        ),
    ]
