# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seresults', '0002_auto_20160426_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='status',
            field=models.IntegerField(default='1', verbose_name='Status'),
        ),
    ]
