# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seresults', '0003_auto_20160426_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data dodania'),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zako\u0144czenia'),
        ),
    ]
